# permissions for end users to view fdus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fdu-viewer-role
rules:
- apiGroups:
  - fdu.fog05.io
  resources:
  - fdus
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fdu.fog05.io
  resources:
  - fdus/status
  verbs:
  - get
