# permissions for end users to edit fdus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fdu-editor-role
rules:
- apiGroups:
  - fdu.fog05.io
  resources:
  - fdus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fdu.fog05.io
  resources:
  - fdus/status
  verbs:
  - get
